server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: employeeModule
          uri: http://localhost:8081/
          predicates:
            - Path=/api/v1/**
        - id: dataModule
          uri: http://localhost:8082/
          predicates:
            - Path=/api/v2/**